// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonthlyBudget.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonthlyBudget.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonthlyBudget.BudgetManagement.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_month");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_excluded");

                    b.Property<bool>("IsSpread")
                        .HasColumnType("boolean")
                        .HasColumnName("is_spread");

                    b.Property<Guid?>("MonthlyBudgetBudgetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExpenseId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("MonthlyBudgetBudgetId");

                    b.ToTable("expenses", "budget");
                });

            modelBuilder.Entity("MonthlyBudget.BudgetManagement.Domain.Entities.IncomeSource", b =>
                {
                    b.Property<Guid>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("income_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MonthlyBudgetBudgetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IncomeId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("MonthlyBudgetBudgetId");

                    b.ToTable("income_sources", "budget");
                });

            modelBuilder.Entity("MonthlyBudget.BudgetManagement.Domain.Entities.MonthlyBudget", b =>
                {
                    b.Property<Guid>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("year_month");

                    b.HasKey("BudgetId");

                    b.HasIndex("HouseholdId", "YearMonth")
                        .IsUnique();

                    b.ToTable("monthly_budgets", "budget");
                });

            modelBuilder.Entity("MonthlyBudget.ForecastEngine.Domain.Entities.DailyEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<decimal>("DailyExpenseTotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("daily_expense_total");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<Guid>("ForecastId")
                        .HasColumnType("uuid")
                        .HasColumnName("forecast_id");

                    b.Property<Guid?>("ForecastVersionForecastId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("remaining_balance");

                    b.HasKey("EntryId");

                    b.HasIndex("ForecastVersionForecastId");

                    b.HasIndex("ForecastId", "DayNumber")
                        .IsUnique();

                    b.ToTable("daily_entries", "forecast");
                });

            modelBuilder.Entity("MonthlyBudget.ForecastEngine.Domain.Entities.DailyExpenseItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("DailyEntryEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("expense_name");

                    b.Property<Guid>("ExpenseSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_snapshot_id");

                    b.HasKey("ItemId");

                    b.HasIndex("DailyEntryEntryId");

                    b.ToTable("daily_expense_items", "forecast");
                });

            modelBuilder.Entity("MonthlyBudget.ForecastEngine.Domain.Entities.ExpenseSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_month");

                    b.Property<Guid>("ForecastId")
                        .HasColumnType("uuid")
                        .HasColumnName("forecast_id");

                    b.Property<Guid?>("ForecastVersionForecastId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_excluded");

                    b.Property<bool>("IsSpread")
                        .HasColumnType("boolean")
                        .HasColumnName("is_spread");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OriginalExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_expense_id");

                    b.HasKey("SnapshotId");

                    b.HasIndex("ForecastVersionForecastId");

                    b.ToTable("expense_snapshots", "forecast");
                });

            modelBuilder.Entity("MonthlyBudget.ForecastEngine.Domain.Entities.ForecastVersion", b =>
                {
                    b.Property<Guid>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("forecast_id");

                    b.Property<decimal?>("ActualBalance")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("actual_balance");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("ForecastDate")
                        .HasColumnType("date")
                        .HasColumnName("forecast_date");

                    b.Property<string>("ForecastType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forecast_type");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsSnapshot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_snapshot");

                    b.Property<Guid?>("ParentForecastId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_forecast_id");

                    b.Property<decimal>("StartBalance")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("start_balance");

                    b.Property<int>("StartDay")
                        .HasColumnType("integer")
                        .HasColumnName("start_day");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version_label");

                    b.HasKey("ForecastId");

                    b.ToTable("forecast_versions", "forecast");
                });

            modelBuilder.Entity("MonthlyBudget.IdentityHousehold.Domain.Entities.Household", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("HouseholdId");

                    b.ToTable("households", "identity");
                });

            modelBuilder.Entity("MonthlyBudget.IdentityHousehold.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("invited_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token");

                    b.HasKey("InvitationId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("invitations", "identity");
                });

            modelBuilder.Entity("MonthlyBudget.IdentityHousehold.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("app_users", "identity");
                });

            modelBuilder.Entity("MonthlyBudget.BudgetManagement.Domain.Entities.Expense", b =>
                {
                    b.HasOne("MonthlyBudget.BudgetManagement.Domain.Entities.MonthlyBudget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonthlyBudget.BudgetManagement.Domain.Entities.MonthlyBudget", null)
                        .WithMany("Expenses")
                        .HasForeignKey("MonthlyBudgetBudgetId");
                });

            modelBuilder.Entity("MonthlyBudget.BudgetManagement.Domain.Entities.IncomeSource", b =>
                {
                    b.HasOne("MonthlyBudget.BudgetManagement.Domain.Entities.MonthlyBudget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonthlyBudget.BudgetManagement.Domain.Entities.MonthlyBudget", null)
                        .WithMany("IncomeSources")
                        .HasForeignKey("MonthlyBudgetBudgetId");
                });

            modelBuilder.Entity("MonthlyBudget.ForecastEngine.Domain.Entities.DailyEntry", b =>
                {
                    b.HasOne("MonthlyBudget.ForecastEngine.Domain.Entities.ForecastVersion", null)
                        .WithMany("DailyEntries")
                        .HasForeignKey("ForecastVersionForecastId");
                });

            modelBuilder.Entity("MonthlyBudget.ForecastEngine.Domain.Entities.DailyExpenseItem", b =>
                {
                    b.HasOne("MonthlyBudget.ForecastEngine.Domain.Entities.DailyEntry", null)
                        .WithMany("ExpenseBreakdown")
                        .HasForeignKey("DailyEntryEntryId");
                });

            modelBuilder.Entity("MonthlyBudget.ForecastEngine.Domain.Entities.ExpenseSnapshot", b =>
                {
                    b.HasOne("MonthlyBudget.ForecastEngine.Domain.Entities.ForecastVersion", null)
                        .WithMany("ExpenseSnapshots")
                        .HasForeignKey("ForecastVersionForecastId");
                });

            modelBuilder.Entity("MonthlyBudget.IdentityHousehold.Domain.Entities.Household", b =>
                {
                    b.OwnsMany("MonthlyBudget.IdentityHousehold.Domain.Entities.Member", "Members", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("member_id");

                            b1.Property<Guid>("HouseholdId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("role");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("MemberId");

                            b1.HasIndex("HouseholdId");

                            b1.ToTable("household_members", "identity");

                            b1.WithOwner()
                                .HasForeignKey("HouseholdId");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("MonthlyBudget.BudgetManagement.Domain.Entities.MonthlyBudget", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("IncomeSources");
                });

            modelBuilder.Entity("MonthlyBudget.ForecastEngine.Domain.Entities.DailyEntry", b =>
                {
                    b.Navigation("ExpenseBreakdown");
                });

            modelBuilder.Entity("MonthlyBudget.ForecastEngine.Domain.Entities.ForecastVersion", b =>
                {
                    b.Navigation("DailyEntries");

                    b.Navigation("ExpenseSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
